### ISSUE TITLE
4.9.1 error: r.contextmenu is not a function && Cannot set property 'isMouseAction' of undefined

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [jspreadsheet/ce#1433]
After upgrading from 4.7.3 to 4.9.1

I get the following error:
![image](https://user-images.githubusercontent.com/1098243/131016818-55aba3c1-6bbe-40e7-9a6b-8e3ab744b54d.png)
I suppose this is somehow caused due to too agressive treeshaking in angular 12.2/webpack 5?
I don't have it if I don't do the build for production

Any ideas?

**Comment by GBonnaire** [comment]
You have same error with 4.9.0 ?

**Comment by LanderBeeuwsaert** [comment]
Hi I just tested it, yes, 4.9.0 is the same.

**Comment by GBonnaire** [comment]
Ok, and try with unminified version, for understand more track.

Sorry, but i can't reproduct your bug.

My first hypothese is problem is on jSuites and not on JSpreadsheet because on createTable, jspreadsheet call function jSuites.contextmenu and maybe you have an requirement not correctly defined for jSuites

**Comment by LanderBeeuwsaert** [comment]
@GBonnaire 
Hi Guillaume, I just tested with 4.9.5 and don't have the exception anymore it seems.
Has something been changed?

**Comment by LanderBeeuwsaert** [comment]
I've tested by going back to 4.9.1, which gave the error again, and then returning to 4.9.5 which solved the issue for a second time. Closing!

**Comment by LanderBeeuwsaert** [comment]
thanks for the fix!

**Comment by GBonnaire** [comment]
> @GBonnaire
> Hi Guillaume, I just tested with 4.9.5 and don't have the exception anymore it seems.
> Has something been changed?

There is a many patch maked by @pphod . Maybe some fix your problem.

Have good day
